---

- name: Download locode database archive
  ansible.builtin.unarchive:
    src: "{{ neofs_ir__locodedb_download_url }}"
    remote_src: yes
    dest: "{{ neofs_ir__data_dir }}"
    owner: "{{ neofs_ir__user }}"
    group: "{{ neofs_ir__group }}"
    mode: '0644'
  notify:
    - Restart neofs-ir{{ neofs_ir__instance }} service
