---

- name: Ensure there is neofs-ir group
  ansible.builtin.group:
    name: "{{ neofs_ir__group }}"
    system: yes
    state: 'present'

- name: Ensure there is neofs-ir user
  ansible.builtin.user:
    name: "{{ neofs_ir__user }}"
    group: "{{ neofs_ir__group }}"
    password: '*'
    shell: /usr/sbin/nologin
    home: "{{ neofs_ir__data_dir }}"
    system: yes
    skeleton: no
    state: 'present'

- name: Get uid for neofs-ir user
  ansible.builtin.getent:
    database: passwd
    key: "{{ neofs_ir__user }}"

- name: Get gid for neofs-ir user
  ansible.builtin.getent:
    database: group
    key: "{{ neofs_ir__group }}"
